required = [
  "github.com/golang/dep/cmd/dep",
  "github.com/jteeuwen/go-bindata/go-bindata",
  "github.com/drycc/go-tuf/cmd/tuf",
  "github.com/drycc/go-tuf/cmd/tuf-client",
]

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = ">= 0.3.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = ">= 1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/drycc/jsonschema"

[[constraint]]
  branch = "master"
  name = "github.com/stevvooe/resumable"
  source = "github.com/drycc/resumable"

[[constraint]]
  branch = "master"
  name = "github.com/docker/docker"
  source = "github.com/drycc/docker"

[[constraint]]
  branch = "master"
  name = "github.com/docker/distribution"
  source = "github.com/drycc/distribution"

[[constraint]]
  branch = "master"
  name = "github.com/drycc/libnetwork"

[[constraint]]
  name = "github.com/docker/go-units"
  version = ">= 0.3.0"

[[constraint]]
  branch = "v1"
  name = "github.com/drycc/go-check"

[[constraint]]
  branch = "master"
  name = "github.com/drycc/go-docopt"

[[constraint]]
  branch = "master"
  name = "github.com/drycc/go-p9p"

[[constraint]]
  branch = "master"
  name = "github.com/drycc/go-tuf"

[[constraint]]
  branch = "master"
  name = "github.com/drycc/que-go"

[[constraint]]
  branch = "master"
  name = "github.com/drycc/tail"

[[constraint]] 
  name = "github.com/jackc/pgx" 
  version = ">= 2.0.0, < 3.0.0"

[[constraint]]
  name = "github.com/hashicorp/raft"
  version = ">= 0.1.0 , < 1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/opencontainers/runc"

[[constraint]]
  name = "github.com/golang/dep"
  version = "v0.5.0"

[[constraint]]
  name = "github.com/inconshreveable/log15"
  version = "2.13.0"

[[constraint]]
  name = "github.com/jtacoma/uritemplates"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/tent/canonical-json-go"

[[constraint]]
  branch = "master"
  name = "github.com/tiborvass/uniline"

[[constraint]]
  name = "github.com/cheggaaa/pb"
  version = ">=1.0.0, < 2.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/vanillahsu/go_reuseport"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sys"
  source = "github.com/golang/sys"

[[constraint]]
  branch = "v0"
  name = "gopkg.in/inconshreveable/go-update.v0"
